{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":1,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/galenit_modulessdk\/authaction\/reseterror"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.galenit.GalenIT-ModulesSDK\/documentation\/GalenIT_ModulesSDK\/AuthAction\/resetError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"No overview available."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetError"}],"title":"AuthAction.resetError","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:18GalenIT_ModulesSDK10AuthActionO10resetErroryA2CmF","modules":[{"name":"GalenIT_ModulesSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.galenit.GalenIT-ModulesSDK\/documentation\/GalenIT_ModulesSDK","doc:\/\/com.galenit.GalenIT-ModulesSDK\/documentation\/GalenIT_ModulesSDK\/AuthAction"]]},"references":{"doc://com.galenit.GalenIT-ModulesSDK/documentation/GalenIT_ModulesSDK/AuthAction":{"role":"symbol","title":"AuthAction","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthAction"}],"abstract":[],"identifier":"doc:\/\/com.galenit.GalenIT-ModulesSDK\/documentation\/GalenIT_ModulesSDK\/AuthAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthAction"}],"url":"\/documentation\/galenit_modulessdk\/authaction"},"doc://com.galenit.GalenIT-ModulesSDK/documentation/GalenIT_ModulesSDK":{"role":"collection","title":"GalenIT_ModulesSDK","abstract":[],"identifier":"doc:\/\/com.galenit.GalenIT-ModulesSDK\/documentation\/GalenIT_ModulesSDK","kind":"symbol","type":"topic","url":"\/documentation\/galenit_modulessdk"},"doc://com.galenit.GalenIT-ModulesSDK/documentation/GalenIT_ModulesSDK/AuthAction/resetError":{"role":"symbol","title":"AuthAction.resetError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetError"}],"abstract":[],"identifier":"doc:\/\/com.galenit.GalenIT-ModulesSDK\/documentation\/GalenIT_ModulesSDK\/AuthAction\/resetError","kind":"symbol","type":"topic","url":"\/documentation\/galenit_modulessdk\/authaction\/reseterror"}}}